name: Deploy Firebase

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Choose environment & create service account file
        shell: bash
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo '${{ secrets.GCP_SERVICE_ACCOUNT_DEV }}' > service-account.json
          else
            echo "ENV=live" >> $GITHUB_ENV
            echo '${{ secrets.GCP_SERVICE_ACCOUNT_PROD }}' > service-account.json
          fi
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/service-account.json" >> $GITHUB_ENV

      - name: Install Functions dependencies
        run: |
          cd functions
          npm install

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          firebase use $ENV
          firebase deploy --only functions,firestore:rules,storage --force