name: Deploy Firebase

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Choose Firebase environment
        run: |
          # Sjekker hvilken branch vi er pÃ¥
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
          else
            echo "ENV=live" >> $GITHUB_ENV
          fi

      - name: Install Functions dependencies
        run: |
          cd functions
          npm install

      - name: Deploy to Firebase
        run: |
          firebase use $ENV
          firebase deploy --only functions,firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
